[package]
name = "shared-rs"
version = "0.1.0"
edition = "2021"

[lib]
# "This must contain at least cdylib for Android libraries to be generated."
# https://github.com/bbqsrc/cargo-ndk/blob/main/example/Cargo.toml
# else:
# [2022-05-16T09:53:58Z INFO  cargo_ndk::cli] Copying libraries to ./jniLibs...
# [2022-05-16T09:53:58Z ERROR cargo_ndk::cli] No .so files found in path
crate-type = ["cdylib"]

[dependencies]
# default-features to disable all std related code?
# "you can basically only use the compose_extrinsic_offline macro."
# maybe see https://github.com/scs/substrate-api-client/issues/166 ?
substrate-api-client = { version = "~0.6.0",  git = "https://github.com/scs/substrate-api-client.git", default-features = false, branch = "polkadot-v0.9.19" }
# [windows] error: failed to run custom build command for `openssl-sys v0.9.73
# Still fails even with Perl(strawberry) cf README
# So for now install Android Studio inside WSL2...
openssl = { version = '0.10', features = ["vendored"] }

# those are for the examples cf https://github.com/scs/substrate-api-client/blob/master/Cargo.toml
# but here need them as part of our public API
# TODO cleanup eg MAYBE we need sp-core NOT the full node-template-runtime
# env_logger = "0.9.0"
# node-template-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-keyring = { version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }
# clap = { version = "2.33", features = ["yaml"] }
# wabt = "0.10.0"

sp-core = { version = "6.0.0", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }

# only for Android
jni = { version = "0.19.0", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11"
log = "0.4"

[features]
default = ["std"]
std = [
	"sp-core/std",
    "substrate-api-client/std",
    "substrate-api-client/ws-client",
]
with-jni = ["jni"]