[package]
name = "circuit-evaluate"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
aes = "0.8.1"

[build-dependencies]
cxx-build = "1.0"
prost-build = "0.10.4"
# we need cmake only b/c we MUST compile libprotobuf ourself
# "prost-build" compiles it if needed, but only for HOST arch, in order to build protoc
# But we MUST link our final Rust package with a TARGET libprotobuf
cmake = "0.1"

[lib]
name = "circuit_evaluate"
# NOTE: that one is NOT meant to be used as Android library; but linked via crate "renderer"
# so it can be a standard Rust's "lib"
crate-type = ["lib"]

[features]
# TODO(rust) no_std
default = ['std']
std = [
    # 'sp-std/std',
]