[package]
name = "circuit-evaluate"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
aes = "0.8.1"

[build-dependencies]
cxx-build = "1.0"
prost-build = "0.10.4"

[lib]
name = "circuit_evaluate"
# DO NOT use staticlib; that prevents from using this crate from circuits_routes.rs etc
# crate-type = ["cdylib", "lib"]
crate-type = ["staticlib", "lib"]

[features]
# TODO(rust) no_std
default = ['std']
std = [
    # 'sp-std/std',
]