name: Build and Test Android App

on:
  push:

jobs:
  ##########################################################################
  ##########################################################################
  rust_lint:
    runs-on: ubuntu-latest
    steps:
      # install build dependencies
      # MUST match the same step in Dockerfile
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: true

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          # ignore the nightly, and use stable for tests and linters
          use_toolchain_toml: false
          toolchain_components: "rustfmt,clippy"
          working-directory: shared/rust

      - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev

      ##########################################################################
      - uses: Interstellar-Network/gh-actions/rust-lint@v3-dev
        with:
          working-directory: shared/rust
          clippy_args: "--all-features -- -D warnings"

        # TODO move into separate action? ideally into a JS action "post" that setup ccache?
        # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: success() || failure()
        run: |
          ccache --show-stats || true
          sccache --show-stats || true
        shell: bash

  ##########################################################################
  ##########################################################################
  rust_test:
    runs-on: ubuntu-latest
    steps:
      # install build dependencies
      # MUST match the same step in Dockerfile
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: true

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          # ignore the nightly, and use stable for tests and linters
          use_toolchain_toml: false
          toolchain_components: "rustfmt,clippy"
          working-directory: shared/rust

      - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev

      ##########################################################################

      # https://github.com/actions/setup-java
      # TODO cache: "/home/runner/.konan"?
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          cache: "gradle"
          distribution: "temurin"
          # cf https://github.com/jni-rs/jni-rs/blob/master/.github/workflows/ci.yml
          # for the version?
          # NOTE: "Error: Could not find satisfied version for SemVer '1.8'.
          # Available versions: 18.0.1+10, 18.0.0+36, 17.0.3+7, 17.0.2+8, 17.0.1+12, 17.0.0+35, 16.0.2+7, 11.0.15+10, 11.0.14+101, 11.0.14+9, 11.0.13+8, 11.0.12+7, 8.0.332+9, 8.0.322+6, 8.0.312+7, 8.0.302+8"
          # java-version: 8.0
          #  * What went wrong:
          # An exception occurred applying plugin request [id: 'com.android.application']
          # > Failed to apply plugin 'com.android.internal.application'.
          #   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
          #     Your current JDK is located in  /usr/lib/jvm/temurin-8-jdk-amd64/jre
          # TODO use Java 17(LTS)
          java-version: 11.0
      - name: DEBUG JAVA_HOME .so
        # WTF is "find" not printing without piping through "cat"??
        run: |
          echo "DEBUG JAVA_HOME .so"
          find $JAVA_HOME -type f -name "*.so*" -print0 | echo "nothing!"
          echo "1"
          echo $(find $JAVA_HOME -type f -name "*.so*" -print0 | echo "nothing!")
          echo "2"
          echo $(find $JAVA_HOME -type f -name "*.so*" -print0 | echo "nothing!") | cat
          echo "3"
          echo "DEBUG JAVA_HOME all files"
          find $JAVA_HOME -type f -print0 | echo "nothing!"
          echo "1"
          echo $(find $JAVA_HOME -type f -print0 | echo "nothing!")
          echo "2"
          echo $(find $JAVA_HOME -type f -print0 | echo "nothing!") | cat
          echo "3"
          echo "done!"
        shell: bash      
      - name: update LD_LIBRARY_PATH for Rust+Java
        # careful with this "find"; usually in CI there are multiple versions installed
        # so DO NOT find in "/usr/lib/jvm" but use JAVA_HOME instead!
        # -> FAIL: no libjvm.so in JAVA_HOME?? [in CI: JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64]
        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /usr/lib/jvm -type f -name libjvm.so -regex '\(.*11.*\)' -printf "%h:")" >> $GITHUB_ENV

      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v3-dev
        with:
          working-directory: shared/rust
          check_args: "--all-features"
          test_args: "--all-features"
        timeout-minutes: 60

        # TODO move into separate action? ideally into a JS action "post" that setup ccache?
        # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: success() || failure()
        run: |
          ccache --show-stats || true
          sccache --show-stats || true
        shell: bash

  ##########################################################################
  ##########################################################################
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # cf https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix
        # list of pairs:
        # - cargo target
        # - gradle_task: eg "assembleXXXRelease"
        # - experimental: a flag passed to "continue-on-error"
        # NOT GET the gradle targets with eg `./gradlew --no-daemon tasks | grep assemble`
        android-target: [
            {
              cargo_target: "aarch64-linux-android",
              gradle_task: "assembleArm64Release",
              apk_artifact_name: "apk-Arm64Release",
              experimental: false,
            },
            {
              cargo_target: "armv7-linux-androideabi",
              gradle_task: "assembleArmv7Release",
              apk_artifact_name: "apk-Armv7Release",
              # TODO? it (was supposed to fail, cf `lib-garble-rs)` b/c of pointer size difference, at least in Scuttlebut
              # but as we are still not in PROD/GA, we only care about aarch64 for now
              experimental: true,
            },
            {
              cargo_target: "x86_64-linux-android",
              gradle_task: "assembleX86_64Debug",
              apk_artifact_name: "apk-X86_64Debug",
              experimental: false,
            },
          ]
    steps:
      # install build dependencies
      # MUST match the same step in Dockerfile
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: true

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          use_toolchain_toml: "true"
          toolchain_toml_path: ${{ github.workspace }}/rust-toolchain.toml
          toolchain_components: ""
          working-directory: shared/rust

      - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev

      ##########################################################################
      # cf https://github.com/android-actions/setup-android

      - run: rustup target add ${{ matrix.android-target.cargo_target }}

      # https://github.com/actions/setup-java
      # TODO cache: "/home/runner/.konan"?
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          cache: "gradle"
          distribution: "temurin"
          # cf https://github.com/jni-rs/jni-rs/blob/master/.github/workflows/ci.yml
          # for the version?
          # NOTE: "Error: Could not find satisfied version for SemVer '1.8'.
          # Available versions: 18.0.1+10, 18.0.0+36, 17.0.3+7, 17.0.2+8, 17.0.1+12, 17.0.0+35, 16.0.2+7, 11.0.15+10, 11.0.14+101, 11.0.14+9, 11.0.13+8, 11.0.12+7, 8.0.332+9, 8.0.322+6, 8.0.312+7, 8.0.302+8"
          # java-version: 8.0
          #  * What went wrong:
          # An exception occurred applying plugin request [id: 'com.android.application']
          # > Failed to apply plugin 'com.android.internal.application'.
          #   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
          #     Your current JDK is located in  /usr/lib/jvm/temurin-8-jdk-amd64/jre
          # TODO use Java 17(LTS)
          java-version: 11.0
      - name: update LD_LIBRARY_PATH for Rust+Java
        # careful with this "find"; usually in CI there are multiple versions installed
        # so DO NOT find in "/usr/lib/jvm" but use JAVA_HOME instead!
        # -> FAIL: no libjvm.so in JAVA_HOME?? [in CI: JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64]
        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /usr/lib/jvm -type f -name libjvm.so -regex '\(.*11.*\)' -printf "%h:")" >> $GITHUB_ENV

      # TODO apparently this is not cached?
      # if not: cache the whole "Setup Android SDK"+"Delete old NDK v23"+"Install NDK v24"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # else: "Warning: Observed package id 'ndk;23.2.8568313' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/23.2.8568313')"
      - name: Delete old NDK v23
        # version required else: "Warning: Failed to find package 'ndk'"
        run: sdkmanager --uninstall "ndk;23.2.8568313"
      - name: Install NDK v25
        # version required else: "Warning: Failed to find package 'ndk'"
        # MUST match version used at NDK_ROOT below! Careful when updating!
        run: sdkmanager "ndk;25.1.8937393"

      - name: Build Wallet-App
        run: ./gradlew --no-daemon ${{ matrix.android-target.gradle_task }}
        # TODO it fails b/c of pointer size difference, at least in Scuttlebut
        # but as we are still not in PROD/GA, we only care about aarch64 for now
        continue-on-error: ${{ matrix.android-target.experimental }}

        # TODO move into separate action? ideally into a JS action "post" that setup ccache?
        # NOTE: remove if using "rust-build-and-test"
      - name: Print ccache/sccache stats
        # display stats even if tests failed
        if: success() || failure()
        run: |
          ccache --show-stats || true
          sccache --show-stats || true
        shell: bash

      # TODO on main/master: it SHOULD be a Release instead of Artifact
      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.android-target.apk_artifact_name }}
          path: ./androidApp/build/outputs/apk/**/**/*.apk
          retention-days: 7
